#!/usr/bin/env bash
git clone --quiet git@github.com:Mty95/magento-development.git mty95

for filename in mty95/docker/bin/*; do
  [ -e "$filename" ] || continue

  mkdir -p bin
  cp -rf $filename ${filename#*/*/}
  chmod +x ${filename#*/*/}
done

rm -r mty95